import { CrmContact } from './types';

const now = '2026-06-19T09:00:00.000Z';

export const demoCrmContacts: CrmContact[] = [
  {
    id: 'demo-crm-001',
    name: 'Анна Соколова',
    phone: '+7 900 000-00-01',
    telegramUsername: 'anna_demo',
    email: 'anna.demo@example.com',
    role: 'owner',
    source: 'form',
    objectsCount: 2,
    city: 'Санкт-Петербург',
    note: 'Хочет начать с одного объекта у метро. Нужна короткая инструкция по данным.',
    status: 'contact',
    communicationStatus: 'waiting_reply',
    lastContactAt: '2026-06-18T12:00:00.000Z',
    nextStep: 'Написать и попросить данные тестового объекта.',
    nextActionAt: '2026-06-20T08:00:00.000Z',
    createdAt: '2026-06-18T10:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-002',
    name: 'Илья Орлов',
    phone: '+7 900 000-00-02',
    telegramUsername: 'ilya_demo',
    email: null,
    role: 'manager',
    source: 'telegram',
    objectsCount: 7,
    city: 'Москва',
    note: 'Управляет несколькими квартирами, интересуется снижением ручных ответов гостям.',
    status: 'instruction_sent',
    communicationStatus: 'replied',
    lastContactAt: '2026-06-19T07:30:00.000Z',
    nextStep: 'Дождаться списка объектов и выбрать пилотный.',
    nextActionAt: '2026-06-21T09:00:00.000Z',
    createdAt: '2026-06-17T13:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-003',
    name: 'Мария Волкова',
    phone: '+7 900 000-00-03',
    telegramUsername: '',
    email: 'maria.demo@example.com',
    role: 'partner',
    source: 'bragin_group',
    objectsCount: 14,
    city: 'Казань',
    note: 'Партнерский контакт. Есть вопрос по роли управляющей компании.',
    status: 'paused',
    communicationStatus: 'needs_manual_reaction',
    lastContactAt: '2026-06-16T15:00:00.000Z',
    nextStep: 'Уточнить формат пилота и кто будет ответственным за данные.',
    nextActionAt: '2026-06-24T10:00:00.000Z',
    createdAt: '2026-06-15T09:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-onb-001',
    name: 'Елена Крылова',
    phone: '+7 900 000-00-05',
    telegramUsername: 'elena_onb',
    email: null,
    role: 'owner',
    source: 'telegram',
    objectsCount: 1,
    city: 'Казань',
    note: [
      'Новый контакт из Telegram.',
      '',
      'Онбординг ASI',
      'Статус: onboarding_started',
      'Город: Казань',
      'Не хватает: адрес объекта, Wi-Fi, каналы',
      'Последнее сообщение: Хочу подключить квартиру к ASI',
      'Менеджер каналов: /dashboard/channel-connections?source=telegram_onboarding',
    ].join('\n'),
    status: 'contact',
    communicationStatus: 'waiting_reply',
    lastContactAt: '2026-06-19T08:10:00.000Z',
    nextStep: 'Запросить: адрес объекта.',
    nextActionAt: '2026-06-20T09:00:00.000Z',
    createdAt: '2026-06-19T08:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-onb-002',
    name: 'Павел Морозов',
    phone: '+7 900 000-00-06',
    telegramUsername: 'pavel_ready',
    email: null,
    role: 'owner',
    source: 'telegram',
    objectsCount: 1,
    city: 'Москва',
    note: [
      'Онбординг ASI',
      'Статус: ready_for_channel_manager',
      'Город: Москва',
      'Не хватает: ничего',
      'Последнее сообщение: Все данные отправил, готов подключать каналы',
      'Менеджер каналов: /dashboard/channel-connections?source=telegram_onboarding',
    ].join('\n'),
    status: 'object_setup',
    communicationStatus: 'waiting_reply',
    lastContactAt: '2026-06-19T08:45:00.000Z',
    nextStep: 'Открыть Менеджер каналов и начать подключение каналов.',
    nextActionAt: '2026-06-20T10:00:00.000Z',
    createdAt: '2026-06-18T14:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-onb-003',
    name: 'Ольга Смирнова',
    phone: '+7 900 000-00-07',
    telegramUsername: 'olga_ops',
    email: null,
    role: 'owner',
    source: 'telegram',
    objectsCount: 1,
    city: 'Сочи',
    note: [
      'Онбординг ASI',
      'Статус: needs_operator',
      'Город: Сочи',
      'Не хватает: фото объекта',
      'Последнее сообщение: Позовите оператора, не понимаю что делать с фото',
      'Менеджер каналов: /dashboard/channel-connections?source=telegram_onboarding',
    ].join('\n'),
    status: 'contact',
    communicationStatus: 'needs_manual_reaction',
    lastContactAt: '2026-06-19T09:15:00.000Z',
    nextStep: 'Оператору нужно ответить вручную по онбордингу объекта.',
    nextActionAt: '2026-06-19T12:00:00.000Z',
    createdAt: '2026-06-17T11:00:00.000Z',
    updatedAt: now,
  },
  {
    id: 'demo-crm-004',
    name: 'Дмитрий Лебедев',
    phone: '+7 900 000-00-04',
    telegramUsername: 'dmitry_demo',
    email: null,
    role: 'owner',
    source: 'manual',
    objectsCount: 1,
    city: 'Сочи',
    note: 'Тестовый объект выбран, ждем доступ к инструкциям и правилам.',
    status: 'test_object_selected',
    communicationStatus: 'wrote_first',
    lastContactAt: '2026-06-18T17:00:00.000Z',
    nextStep: 'Проверить полученные данные и перевести объект на настройку.',
    nextActionAt: '2026-06-20T11:00:00.000Z',
    createdAt: '2026-06-14T11:00:00.000Z',
    updatedAt: now,
  },
];
