import type { RoadmapDepartment, RoadmapStage } from './types';

/** Last limited audit of main evidence for this roadmap snapshot. */
export const ROADMAP_LAST_AUDITED_AT = '2026-08-04';

const reviewed = ROADMAP_LAST_AUDITED_AT;

function stage(
  partial: Omit<RoadmapStage, 'lastReviewedAt'> & { lastReviewedAt?: string },
): RoadmapStage {
  return {
    lastReviewedAt: partial.lastReviewedAt ?? reviewed,
    ...partial,
  };
}

/**
 * Version-controlled source of truth for ASI Product Roadmap Dashboard v1.
 * Statuses must be backed by code, tests, docs, or UI — not types/placeholders alone.
 */
export const ASI_PRODUCT_ROADMAP: RoadmapDepartment[] = [
  {
    id: 'crm-owners',
    title: 'CRM и подключение владельцев',
    description: 'Заявки, CRM-очередь и этапы подключения пилотного владельца.',
    stages: [
      stage({
        id: 'crm-lead-intake',
        title: 'Получение заявки',
        status: 'done',
        currentState: 'Публичная форма и CRM-лиды создают заявку в кабинете.',
        nextStep: 'Держать единый CRM-контакт на пилотного участника.',
        priority: 4,
        dashboardHref: '/dashboard/leads',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/leads/page.tsx' },
          { kind: 'code', path: 'src/lib/crm/repository.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'Этап 1 ready' },
        ],
      }),
      stage({
        id: 'crm-workspace',
        title: 'CRM',
        status: 'done',
        currentState: 'Очередь и карточки CRM доступны операторам.',
        nextStep: 'Использовать существующие статусы онбординга без redesign.',
        priority: 4,
        dashboardHref: '/dashboard/crm',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/crm/page.tsx' },
          { kind: 'ui', path: 'src/app/dashboard/crm/queue/page.tsx' },
          { kind: 'code', path: 'src/lib/crm/types.ts' },
        ],
      }),
      stage({
        id: 'crm-onboarding-stages',
        title: 'Этапы подключения',
        status: 'done',
        currentState: 'Многошаговый onboarding владельца и ops-v17 шаги реализованы.',
        nextStep: 'Проходить инструкцию → доступ → тестовый объект → готов к настройке.',
        priority: 3,
        dashboardHref: '/dashboard/onboarding',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/onboarding/page.tsx' },
          { kind: 'code', path: 'src/lib/ops-v17/service.ts' },
          { kind: 'docs', path: 'docs/OPS_V17_ZERO_TOUCH_PILOT_ONBOARDING.md' },
        ],
      }),
      stage({
        id: 'crm-pilot-owner-activation',
        title: 'Активация пилотного владельца',
        status: 'in_progress',
        currentState: 'Admin-активация и pilot-chain есть; zero-touch ещё не закрыт.',
        nextStep: 'Закрыть ручные пробелы активации для 3–5 пилотных клиентов.',
        priority: 2,
        dashboardHref: '/dashboard/onboarding',
        evidence: [
          { kind: 'code', path: 'src/lib/ops-v17/service.ts', note: 'admin activation' },
          { kind: 'code', path: 'src/lib/pilot-chain' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'semi_ready UX пилота' },
        ],
      }),
    ],
  },
  {
    id: 'property-knowledge',
    title: 'Объекты и база знаний',
    description: 'Паспорт объекта, знания для гостя и готовность к пилоту.',
    stages: [
      stage({
        id: 'prop-card',
        title: 'Карточка объекта',
        status: 'done',
        currentState: 'Карточки объектов и property-knowledge intake работают.',
        nextStep: 'Заполнять паспорт на каждый пилотный объект.',
        priority: 3,
        dashboardHref: '/dashboard/properties',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/properties/page.tsx' },
          { kind: 'ui', path: 'src/app/dashboard/property-knowledge/page.tsx' },
        ],
      }),
      stage({
        id: 'prop-access-rules',
        title: 'Адрес, правила, Wi-Fi и доступ',
        status: 'done',
        currentState: 'Структурированные поля адреса, правил и доступа в knowledge-контуре.',
        nextStep: 'Проверять полноту перед pre-check-in.',
        priority: 3,
        dashboardHref: '/dashboard/property-knowledge',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/property-knowledge-intake.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'раздел B' },
        ],
      }),
      stage({
        id: 'prop-photos-description',
        title: 'Фотографии и описание',
        status: 'in_progress',
        currentState: 'Описание и счётчик фото есть; полноценной media CMS нет.',
        nextStep: 'На пилоте фото можно отложить явной отметкой.',
        priority: 4,
        dashboardHref: '/dashboard/property-knowledge',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'фото deferrable' },
          { kind: 'ui', path: 'src/app/dashboard/property-knowledge/page.tsx' },
        ],
      }),
      stage({
        id: 'prop-readiness',
        title: 'Готовность объекта',
        status: 'done',
        currentState: 'Readiness engine и панели готовности подключены.',
        nextStep: 'Использовать readiness как gate перед гостем.',
        priority: 3,
        dashboardHref: '/dashboard/properties',
        evidence: [
          { kind: 'code', path: 'src/lib/object-readiness' },
          { kind: 'code', path: 'src/lib/pilot-readiness' },
        ],
      }),
      stage({
        id: 'prop-pricing-grid',
        title: 'Структурированные цены и тарифная сетка',
        status: 'in_progress',
        currentState: 'Pricing intelligence / prep есть; живая тарифная сетка не подтверждена.',
        nextStep: 'Фиксировать цену пилота вручную в заметке или менеджере каналов.',
        priority: 2,
        dashboardHref: '/dashboard/properties',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/pricing-intelligence-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'нет structured price field' },
        ],
      }),
    ],
  },
  {
    id: 'channel-ota',
    title: 'Менеджеры каналов и OTA',
    description: 'Подключение каналов, импорт и публикация доступности.',
    stages: [
      stage({
        id: 'ch-connection-model',
        title: 'Модель подключения',
        status: 'done',
        currentState: 'Выбор провайдера и состояния подключения в dashboard.',
        nextStep: 'Вести пилот через prepared → manual connected.',
        priority: 3,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/channel-connections/page.tsx' },
          { kind: 'code', path: 'src/lib/channel-manager-connection' },
        ],
      }),
      stage({
        id: 'ch-safe-credentials-link',
        title: 'Безопасная ссылка на credentials',
        status: 'done',
        currentState: 'Хранится safe_access_ref; пароли в импорте отклоняются.',
        nextStep: 'Принимать только ссылку/реф доступа, не секреты в чат.',
        priority: 3,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'safe_access_ref' },
          { kind: 'docs', path: 'docs/OPS_V17_ZERO_TOUCH_PILOT_ONBOARDING.md' },
        ],
      }),
      stage({
        id: 'ch-manual-json-import',
        title: 'Ручной JSON-import',
        status: 'done',
        currentState: 'Manual adapter и UI-импорт снимка реально работают.',
        nextStep: 'Импортировать snapshot для пилотного объекта.',
        priority: 2,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'manual adapter' },
          { kind: 'ui', path: 'src/components/booking-ops/ChannelManagerImportPanel.tsx' },
          { kind: 'api', path: 'src/app/api/dashboard/channel-manager' },
        ],
      }),
      stage({
        id: 'ch-object-mapping',
        title: 'Сопоставление объектов',
        status: 'in_progress',
        currentState: 'Reconcile imported objects при ручном импорте есть.',
        nextStep: 'Довести mapping до устойчивого live-контура.',
        priority: 2,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'reconcileImportedObjects' },
        ],
      }),
      stage({
        id: 'ch-booking-dedup',
        title: 'Сопоставление и защита от дублей броней',
        status: 'done',
        currentState: 'Idempotent upsert по external_booking_id при импорте.',
        nextStep: 'Сохранять внешние ID при любом ручном импорте.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'external_booking_id upsert' },
          { kind: 'code', path: 'src/lib/booking-ops/real-booking-intake-autopilot.ts' },
        ],
      }),
      stage({
        id: 'ch-live-core',
        title: 'Channel Manager Live Core',
        status: 'later',
        currentState: 'Есть контракт ChannelManagerLiveAdapter, реализации live нет.',
        nextStep: 'После пилота реализовать live core поверх ручного контура.',
        priority: 5,
        blocker: 'Live adapter — только интерфейс, не готовность.',
        evidence: [
          { kind: 'code', path: 'src/lib/ops-v17/types.ts', note: 'ChannelManagerLiveAdapter' },
          { kind: 'docs', path: 'docs/OPS_V17_ZERO_TOUCH_PILOT_ONBOARDING.md' },
        ],
      }),
      stage({
        id: 'ch-initial-incremental-sync',
        title: 'Initial и incremental sync',
        status: 'later',
        currentState: 'Живой initial/incremental sync с провайдерами отсутствует.',
        nextStep: 'Планировать после первого real provider adapter.',
        priority: 5,
        blocker: 'Нет real API adapters Bnovo / RealtyCalendar / TravelLine.',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'supports_real_api: false' },
          { kind: 'docs', path: 'docs/market-signals-ingestion-v1.md' },
        ],
      }),
      stage({
        id: 'ch-booking-changes-cancels',
        title: 'Изменения и отмены броней',
        status: 'in_progress',
        currentState: 'Внутренние update/cancel есть; push отмены в OTA нет.',
        nextStep: 'На пилоте фиксировать изменения вручную + внутренний cancel.',
        priority: 3,
        dashboardHref: '/dashboard/reservations',
        evidence: [
          { kind: 'code', path: 'src/lib/reservations/ledger.ts', note: 'cancelReservation' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
      stage({
        id: 'ch-first-real-adapter',
        title: 'Первый реальный provider adapter',
        status: 'blocked',
        currentState: 'Bnovo, RealtyCalendar и TravelLine помечены unavailable / no real API.',
        nextStep: 'Выбрать первого провайдера и закрыть credentials + API contract.',
        priority: 1,
        blocker: 'Реальные API Bnovo, RealtyCalendar и TravelLine отсутствуют.',
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts', note: 'unavailableAdapter' },
          { kind: 'docs', path: 'docs/channel-manager-access-import-v1.md' },
        ],
      }),
      stage({
        id: 'ch-calendar-reconcile',
        title: 'Сверка календаря',
        status: 'in_progress',
        currentState: 'Snapshot reconcile и run_reconciliation доступны; live pull нет.',
        nextStep: 'Сверять календарь после каждого ручного импорта.',
        priority: 2,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'api', path: 'src/app/api/dashboard/channel-manager/reconcile/route.ts' },
        ],
      }),
      stage({
        id: 'ch-outbound-publish',
        title: 'Outbound-публикация цен и доступности',
        status: 'blocked',
        currentState: 'Только preparation package; realOtaPublishingEnabled всегда false.',
        nextStep: 'Не считать prepared публикацией; публиковать вручную вне ASI.',
        priority: 1,
        blocker: 'Outbound OTA publication отсутствует.',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-publishing-preparation.ts', note: 'realOtaPublishingEnabled: false' },
          { kind: 'docs', path: 'docs/channel-publishing-preparation-v1.md' },
        ],
      }),
    ],
  },
  {
    id: 'bookings-calendar',
    title: 'Бронирования и календарь',
    description: 'Приём брони, единый календарь и lifecycle Booking Ops.',
    stages: [
      stage({
        id: 'bk-manual-admin-create',
        title: 'Ручное/admin-создание брони',
        status: 'done',
        currentState: 'Admin/manual create path в Booking Ops подтверждён.',
        nextStep: 'Создавать пилотные брони через dashboard admin/import.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/repository.ts', note: 'createBookingOpsRecord' },
          { kind: 'api', path: 'src/app/api/dashboard/booking-ops/route.ts' },
        ],
      }),
      stage({
        id: 'bk-booking-intake',
        title: 'Booking Intake',
        status: 'done',
        currentState: 'Multi-source intake autopilot (web/telegram/dashboard) реализован.',
        nextStep: 'Проверять идемпотентность внешних ID при intake.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/real-booking-intake-autopilot.ts' },
          { kind: 'test', path: 'src/lib/booking-ops/__tests__/real-booking-intake-autopilot.test.ts' },
        ],
      }),
      stage({
        id: 'bk-unified-calendar',
        title: 'Единый календарь',
        status: 'done',
        currentState: 'Страница /dashboard/reservations — единый календарь броней.',
        nextStep: 'Сверять календарь с ручным OTA-снимком.',
        priority: 3,
        dashboardHref: '/dashboard/reservations',
        evidence: [
          { kind: 'ui', path: 'src/app/dashboard/reservations/page.tsx' },
          { kind: 'code', path: 'src/lib/reservations' },
        ],
      }),
      stage({
        id: 'bk-lifecycle',
        title: 'Lifecycle бронирования',
        status: 'done',
        currentState: 'Booking Ops lifecycle, gates и automation runner существуют.',
        nextStep: 'Проходить gates по регламенту пилота.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/lifecycle.ts' },
          { kind: 'code', path: 'src/lib/booking-ops/lifecycle-orchestrator.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
      stage({
        id: 'bk-overbooking-protection',
        title: 'Защита от овербукинга',
        status: 'done',
        currentState: 'Conflict checks и block hooks на availability реализованы.',
        nextStep: 'Не обходить availability checks на пилоте.',
        priority: 2,
        dashboardHref: '/dashboard/reservations',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/availability-overbooking-protection.ts' },
        ],
      }),
      stage({
        id: 'bk-external-update-cancel',
        title: 'Обновление и отмена внешней брони',
        status: 'in_progress',
        currentState: 'Внутренний контур есть; outbound OTA cancel/update нет.',
        nextStep: 'Синхронизировать внешние изменения вручную до real adapter.',
        priority: 3,
        blocker: 'Нет live push изменений/отмен в OTA.',
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/reservations/ledger.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
      stage({
        id: 'bk-reconciliation',
        title: 'Reconciliation',
        status: 'in_progress',
        currentState: 'Domain/lifecycle reconciliation сильный; внешний OTA — слабый.',
        nextStep: 'Запускать reconcile после импорта и при расхождениях.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/lifecycle-reconciliation.ts' },
          { kind: 'test', path: 'src/lib/booking-ops/__tests__/lifecycle-reconciliation.test.ts' },
        ],
      }),
    ],
  },
  {
    id: 'communication-minigpt',
    title: 'Коммуникация и MiniGPT',
    description: 'Telegram, маршрутизация интентов и безопасный LLM-слой.',
    stages: [
      stage({
        id: 'comm-telegram-ingress',
        title: 'Telegram ingress',
        status: 'done',
        currentState: 'Production-shaped Telegram pipeline и webhook/poller контур есть.',
        nextStep: 'Держать ingress в штатном режиме для пилота.',
        priority: 2,
        dashboardHref: '/dashboard/communication',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/orchestrator.ts' },
          { kind: 'api', path: 'src/app/api/telegram' },
        ],
      }),
      stage({
        id: 'comm-role-intent-routing',
        title: 'Маршрутизация ролей и интентов',
        status: 'done',
        currentState: 'Identity routing и guest intent router реализованы.',
        nextStep: 'Проверять эскалации при неоднозначных интентах.',
        priority: 3,
        dashboardHref: '/dashboard/communication',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/communication-identity-routing.ts' },
          { kind: 'code', path: 'src/lib/communication/guest-intent-router.ts' },
        ],
      }),
      stage({
        id: 'comm-property-data-replies',
        title: 'Ответы из данных объекта',
        status: 'done',
        currentState: 'Ответы строятся из property knowledge / шаблонов check-in.',
        nextStep: 'Держать knowledge объекта актуальным.',
        priority: 3,
        dashboardHref: '/dashboard/property-knowledge',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/orchestrator.ts' },
          { kind: 'code', path: 'src/lib/booking-ops/property-knowledge-intake.ts' },
        ],
      }),
      stage({
        id: 'comm-minigpt-safe-domain',
        title: 'MiniGPT safe-domain layer',
        status: 'done',
        currentState: 'Guarded LLM safe-domain layer существует и покрыт тестами.',
        nextStep: 'Не путать наличие слоя с production activation.',
        priority: 3,
        evidence: [
          { kind: 'code', path: 'src/lib/communication/llm-safe-domain-layer.ts' },
          { kind: 'test', path: 'src/lib/communication/__tests__' },
        ],
      }),
      stage({
        id: 'comm-production-llm',
        title: 'Production LLM activation',
        status: 'in_progress',
        currentState: 'Код готов; env-gates по умолчанию выключены — live activation не подтверждена.',
        nextStep: 'Включать только с evidence live-прогона и allowlist.',
        priority: 2,
        blocker: 'Без подтверждённого production evidence нельзя считать LLM activated.',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/llm-safe-domain-layer.ts', note: 'LLM_SAFE_DOMAIN_ENABLED default off' },
          { kind: 'docs', path: 'docs/telegram-llm-router.md', note: 'LLM env-gated; production activation not proven' },
        ],
      }),
      stage({
        id: 'comm-prompt-injection',
        title: 'Prompt-injection protection',
        status: 'done',
        currentState: 'Явный telegram-prompt-injection-guard с block/escalate.',
        nextStep: 'Сохранять fail-closed поведение на пилоте.',
        priority: 2,
        evidence: [
          { kind: 'code', path: 'src/lib/communication/telegram-prompt-injection-guard.ts' },
        ],
      }),
      stage({
        id: 'comm-safe-auto-send',
        title: 'Безопасный auto-send',
        status: 'in_progress',
        currentState: 'Policy safe_to_auto_send есть; часто draft + ручное подтверждение.',
        nextStep: 'Не считать intent фактической доставкой.',
        priority: 2,
        evidence: [
          { kind: 'code', path: 'src/lib/communication/approval.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'draft ≠ delivery' },
        ],
      }),
      stage({
        id: 'comm-delivery-confirmation',
        title: 'Delivery confirmation',
        status: 'in_progress',
        currentState: 'Mark-sent / approval path есть; автоматическое подтверждение каналов неполное.',
        nextStep: 'Оператор подтверждает отправку, если auto-send не применим.',
        priority: 2,
        dashboardHref: '/dashboard/communication',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/approval.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 11' },
        ],
      }),
      stage({
        id: 'comm-operator-escalation',
        title: 'Operator escalation',
        status: 'done',
        currentState: 'Escalation modes и operator review path реализованы.',
        nextStep: 'Использовать escalation при blocked/failed коммуникации.',
        priority: 3,
        dashboardHref: '/dashboard/communication',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/escalations.ts' },
          { kind: 'test', path: 'src/lib/communication/__tests__/escalations.test.ts' },
        ],
      }),
      stage({
        id: 'comm-dialog-memory',
        title: 'Память диалога',
        status: 'done',
        currentState: 'Telegram session memory и comm-agent session memory есть.',
        nextStep: 'Проверять контекст на длинных пилотных диалогах.',
        priority: 4,
        evidence: [
          { kind: 'code', path: 'src/lib/communication/telegram-session-memory.ts' },
        ],
      }),
    ],
  },
  {
    id: 'legal-payments-mvd',
    title: 'Договоры, платежи и МВД',
    description: 'Документы гостя, договор, депозит и МВД — в основном manual/placeholder.',
    stages: [
      stage({
        id: 'legal-docs-request',
        title: 'Запрос и проверка документов',
        status: 'done',
        currentState: 'Autopilot request/receive/verify документов гостя работает.',
        nextStep: 'Проверку документов на пилоте оставлять ручной.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts', note: 'requestGuestDocuments' },
        ],
      }),
      stage({
        id: 'legal-contract-prep',
        title: 'Подготовка договора',
        status: 'done',
        currentState: 'prepareContract и gate contract_prepared существуют.',
        nextStep: 'Готовить договор в ASI, подпись — вне системы.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts', note: 'prepareContract' },
        ],
      }),
      stage({
        id: 'legal-e-sign',
        title: 'Реальная электронная подпись',
        status: 'blocked',
        currentState: 'Только sent_for_signature_placeholder / signed_manual.',
        nextStep: 'Подписывать договор вручную (вне OkiDoki/провайдера).',
        priority: 1,
        blocker: 'Нет OkiDoki и реальной e-signature интеграции.',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 7 placeholder_only' },
        ],
      }),
      stage({
        id: 'legal-deposit-request',
        title: 'Запрос депозита',
        status: 'in_progress',
        currentState: 'Запрос депозита и manual paid статусы есть.',
        nextStep: 'Отправлять реквизиты вручную и подтверждать поступление.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 8' },
        ],
      }),
      stage({
        id: 'legal-payment-provider',
        title: 'Платёжный провайдер',
        status: 'blocked',
        currentState: 'Booking deposits — provider placeholders; YooKassa в billing — не депозиты брони.',
        nextStep: 'Не выдавать billing stub за депозитный PSP.',
        priority: 1,
        blocker: 'Нет платёжного провайдера для депозитов бронирования.',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'нет платёжного провайдера' },
          { kind: 'ui', path: 'src/app/dashboard/billing/page.tsx', note: 'comm pilot pending, не booking deposits' },
        ],
      }),
      stage({
        id: 'legal-deposit-confirm-refund',
        title: 'Подтверждение и возврат депозита',
        status: 'in_progress',
        currentState: 'paid_manual / refunded_manual; деньги вне ASI.',
        nextStep: 'Отмечать поступление и возврат вручную после осмотра.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 13' },
        ],
      }),
      stage({
        id: 'legal-mvd-prep',
        title: 'Подготовка МВД',
        status: 'in_progress',
        currentState: 'prepareMvdReport готовит данные; отправка внешняя.',
        nextStep: 'Готовить пакет в ASI и отправлять вне системы.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/legal-payment-autopilot.ts', note: 'prepareMvdReport' },
        ],
      }),
      stage({
        id: 'legal-mvd-external-send',
        title: 'Реальная внешняя отправка МВД',
        status: 'blocked',
        currentState: 'Только mark_mvd_submitted_manual / provider placeholder.',
        nextStep: 'Отправлять МВД вне ASI и отмечать результат.',
        priority: 1,
        blocker: 'Нет внешней отправки МВД.',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 9 placeholder_only' },
        ],
      }),
    ],
  },
  {
    id: 'stay-flow',
    title: 'Заезд, проживание и выезд',
    description: 'Pre-check-in, stay и checkout контуры Booking Ops.',
    stages: [
      stage({
        id: 'stay-pre-checkin',
        title: 'Pre-check-in readiness',
        status: 'done',
        currentState: 'Pre-check-in control center и blockers реализованы.',
        nextStep: 'Закрывать blockers до заезда.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/pre-checkin-control-center.ts' },
          { kind: 'api', path: 'src/app/api/dashboard/booking-ops' },
        ],
      }),
      stage({
        id: 'stay-guest-instructions',
        title: 'Инструкции гостю',
        status: 'done',
        currentState: 'Check-in instructions в execution autopilot.',
        nextStep: 'Подтверждать фактическую доставку инструкций.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/checkin-execution-autopilot.ts' },
        ],
      }),
      stage({
        id: 'stay-arrival-confirm',
        title: 'Подтверждение прибытия',
        status: 'done',
        currentState: 'Arrival confirmation step в check-in execution.',
        nextStep: 'Отмечать прибытие оператором/гостем по регламенту.',
        priority: 3,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/checkin-execution-autopilot.ts' },
        ],
      }),
      stage({
        id: 'stay-access-checkin',
        title: 'Доступ и факт заезда',
        status: 'done',
        currentState: 'Access + checked-in transitions подтверждены.',
        nextStep: 'При проблеме доступа эскалировать оператору.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/checkin-execution-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 12 ready' },
        ],
      }),
      stage({
        id: 'stay-in-stay-requests',
        title: 'Обращения во время проживания',
        status: 'done',
        currentState: 'In-stay issues контур в instay-checkout-autopilot.',
        nextStep: 'Вести обращения через Booking Ops / communication.',
        priority: 3,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/instay-checkout-autopilot.ts' },
        ],
      }),
      stage({
        id: 'stay-checkout',
        title: 'Выезд',
        status: 'done',
        currentState: 'Checkout gates и действия оператора есть.',
        nextStep: 'Отмечать выезд до осмотра и возврата депозита.',
        priority: 3,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/instay-checkout-autopilot.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 13' },
        ],
      }),
      stage({
        id: 'stay-inspection',
        title: 'Осмотр',
        status: 'done',
        currentState: 'Inspection task/gate в lifecycle и physical readiness.',
        nextStep: 'Не закрывать бронь до осмотра.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
        ],
      }),
      stage({
        id: 'stay-booking-close',
        title: 'Закрытие брони',
        status: 'done',
        currentState: 'markBookingClosed с gate booking_closed.',
        nextStep: 'Финальная ручная проверка перед close.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/instay-checkout-autopilot.ts', note: 'markBookingClosed' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 14' },
        ],
      }),
    ],
  },
  {
    id: 'ops-cleaning',
    title: 'Уборка и эксплуатация',
    description: 'Уборка, бельё, осмотр, мастер и readiness перед следующим гостем.',
    stages: [
      stage({
        id: 'ops-cleaning',
        title: 'Уборка',
        status: 'done',
        currentState: 'Cleaning task type и turnover activation подключены.',
        nextStep: 'Завершать уборку в существующих задачах.',
        priority: 2,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
          { kind: 'test', path: 'src/lib/booking-ops/__tests__/turnover-cleaning-activation.test.ts' },
        ],
      }),
      stage({
        id: 'ops-linen',
        title: 'Бельё',
        status: 'done',
        currentState: 'Linen task type в physical readiness / ops контуре.',
        nextStep: 'Закрывать бельё до readiness gate.',
        priority: 3,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 10 ready' },
        ],
      }),
      stage({
        id: 'ops-inspection-task',
        title: 'Осмотр',
        status: 'done',
        currentState: 'Inspection как operational task подтверждён.',
        nextStep: 'Связывать осмотр с закрытием брони.',
        priority: 3,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
        ],
      }),
      stage({
        id: 'ops-master-repair',
        title: 'Мастер и ремонт',
        status: 'done',
        currentState: 'Maintenance/master task type; незакрытый ремонт блокирует readiness.',
        nextStep: 'Создавать мастер только при реальной проблеме.',
        priority: 3,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'этап 10' },
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
        ],
      }),
      stage({
        id: 'ops-assignee',
        title: 'Назначение исполнителя',
        status: 'in_progress',
        currentState: 'Assign path есть; часто остаётся ручным.',
        nextStep: 'Назначать исполнителя явно на каждую задачу пилота.',
        priority: 3,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/operator-exception-actions.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'назначение может быть ручным' },
        ],
      }),
      stage({
        id: 'ops-executor-comm',
        title: 'Коммуникация с исполнителем',
        status: 'in_progress',
        currentState: 'Draft/intent для cleaning/linen/maintenance; доставка не всегда auto.',
        nextStep: 'Подтверждать фактическую доставку исполнителю.',
        priority: 3,
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/operator-exception-actions.ts' },
        ],
      }),
      stage({
        id: 'ops-physical-completion',
        title: 'Подтверждение физического выполнения',
        status: 'done',
        currentState: 'Completion transitions и physical readiness pack есть.',
        nextStep: 'Не отмечать ready без подтверждения выполнения.',
        priority: 2,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/physical-readiness-execution.ts' },
          { kind: 'test', path: 'src/lib/booking-ops/__tests__/physical-readiness-closure.test.ts' },
        ],
      }),
      stage({
        id: 'ops-next-guest-readiness',
        title: 'Readiness перед следующим гостем',
        status: 'done',
        currentState: 'Readiness gate блокирует следующий заезд при неготовности.',
        nextStep: 'Проверять gate перед каждым pre-check-in.',
        priority: 2,
        dashboardHref: '/dashboard/booking-ops',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/readiness-gate.ts' },
        ],
      }),
    ],
  },
  {
    id: 'pilot-monetization',
    title: 'Пилот и монетизация',
    description: 'Закрытый пилот, реальные брони и платное подключение.',
    stages: [
      stage({
        id: 'pilot-manual-e2e',
        title: 'Ручной демонстрационный E2E',
        status: 'in_progress',
        currentState: 'Pilot loop runnable с обязательными ручными шагами OTA/legal/pay.',
        nextStep: 'Пройти demo E2E по pilot-core-loop регламенту.',
        priority: 1,
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'ready_with_manual_steps' },
        ],
      }),
      stage({
        id: 'pilot-real-mk-booking',
        title: 'Настоящая бронь из МК',
        status: 'in_progress',
        currentState: 'Возможна через ручной JSON-import / admin; не через live MK API.',
        nextStep: 'Импортировать реальную бронь snapshot-ом.',
        priority: 1,
        blocker: 'Нет real provider adapter для автоматического приёма из МК.',
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'code', path: 'src/lib/booking-ops/channel-manager-access-import.ts' },
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
      stage({
        id: 'pilot-real-telegram-guest',
        title: 'Реальный Telegram-диалог гостя',
        status: 'in_progress',
        currentState: 'Контур guest Telegram есть; live dialog зависит от деплоя и activation.',
        nextStep: 'Провести один реальный гостевой диалог на пилоте с подтверждением доставки.',
        priority: 1,
        dashboardHref: '/dashboard/communication',
        evidence: [
          { kind: 'code', path: 'src/lib/communication/orchestrator.ts' },
          { kind: 'test', path: 'src/lib/communication/__tests__/comm-v1-automated-acceptance.test.ts' },
        ],
      }),
      stage({
        id: 'pilot-first-connected-object',
        title: 'Первый подключённый объект',
        status: 'in_progress',
        currentState: 'Connection model и placeholder connected; live connect не подтверждён.',
        nextStep: 'Закрыть один объект в ручном connected режиме.',
        priority: 1,
        dashboardHref: '/dashboard/channel-connections',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'connected объясняет ручной режим' },
        ],
      }),
      stage({
        id: 'pilot-closed-3-5',
        title: 'Закрытый пилот на 3–5 клиентах',
        status: 'in_progress',
        currentState: 'Регламент и готовность к пилоту есть; закрытый cohort ещё не завершён.',
        nextStep: 'Провести 3–5 клиентов по полному циклу с ручными шагами.',
        priority: 1,
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
      stage({
        id: 'pilot-paid-connect',
        title: 'Платное подключение',
        status: 'later',
        currentState: 'Платное early-connect убрано с пилотной формы; продукт не закрыт.',
        nextStep: 'Вернуться после закрытого пилота.',
        priority: 5,
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'paid early-connect removed' },
        ],
      }),
      stage({
        id: 'pilot-support',
        title: 'Сопровождение',
        status: 'in_progress',
        currentState: 'Ops/CRM/communication контуры для сопровождения есть.',
        nextStep: 'Закрепить короткий операционный регламент на пилот.',
        priority: 2,
        dashboardHref: '/dashboard/ops',
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md', note: 'раздел I UX' },
        ],
      }),
      stage({
        id: 'pilot-feedback',
        title: 'Сбор обратной связи',
        status: 'later',
        currentState: 'Отдельного закрытого feedback-контура в roadmap v1 нет.',
        nextStep: 'Собрать feedback вручную на пилоте, затем оформить процесс.',
        priority: 5,
        evidence: [
          { kind: 'docs', path: 'docs/pilot-core-loop-readiness-v1.md' },
        ],
      }),
    ],
  },
  {
    id: 'runtime-dev-factory',
    title: 'Runtime и фабрика разработки',
    description: 'ASI Runtime Bridge, owner console и будущая multi-executor фабрика.',
    stages: [
      stage({
        id: 'rt-single-executor',
        title: 'Одиночный executor',
        status: 'done',
        currentState: 'Runtime Bridge — single runner FIFO с advisory lock.',
        nextStep: 'Держать один running task; не параллелить без pool.',
        priority: 3,
        dashboardHref: '/dashboard/development',
        evidence: [
          { kind: 'docs', path: 'docs/asi-chat-runtime-bridge-v1.md' },
          { kind: 'code', path: 'src/lib/asi-runtime' },
        ],
      }),
      stage({
        id: 'rt-terminal-reconciliation',
        title: 'Terminal-state reconciliation',
        status: 'done',
        currentState: 'Terminal result schema и reconciliation одиночной задачи есть.',
        nextStep: 'Проверять terminal status в owner console.',
        priority: 3,
        dashboardHref: '/dashboard/development',
        evidence: [
          { kind: 'code', path: 'src/lib/asi-runtime' },
          { kind: 'test', path: 'src/lib/asi-runtime/__tests__/bridge.test.ts' },
        ],
      }),
      stage({
        id: 'rt-failure-evidence',
        title: 'Понятные failure evidence',
        status: 'in_progress',
        currentState: 'Safe failure/result schemas есть; полнота operator-facing evidence ещё дорабатывается.',
        nextStep: 'Усилить человекочитаемые failure evidence без сырых логов в чат.',
        priority: 2,
        dashboardHref: '/dashboard/development',
        evidence: [
          { kind: 'docs', path: 'docs/asi-chat-runtime-bridge-v1.md' },
          { kind: 'code', path: 'src/lib/asi-runtime' },
        ],
      }),
      stage({
        id: 'rt-partial-result',
        title: 'Сохранение partial result',
        status: 'in_progress',
        currentState: 'Частичные результаты предусматриваются bridge-схемами; полный UX не закрыт.',
        nextStep: 'Зафиксировать partial result в owner console при interrupted runs.',
        priority: 3,
        dashboardHref: '/dashboard/development',
        evidence: [
          { kind: 'code', path: 'src/lib/asi-runtime' },
        ],
      }),
      stage({
        id: 'rt-worker-pool',
        title: 'Worker pool',
        status: 'later',
        currentState: 'Только single-executor v1; worker pool не реализован.',
        nextStep: 'После стабилизации single runner.',
        priority: 5,
        blocker: 'Архитектура v1 явно single-executor.',
        evidence: [
          { kind: 'docs', path: 'docs/asi-chat-runtime-bridge-v1.md' },
        ],
      }),
      stage({
        id: 'rt-dag-decomposition',
        title: 'Декомпозиция задачи на DAG',
        status: 'later',
        currentState: 'DAG orchestration не найдена в runtime.',
        nextStep: 'Планировать после worker pool.',
        priority: 5,
        evidence: [
          { kind: 'docs', path: 'docs/asi-chat-runtime-bridge-v1.md' },
        ],
      }),
      stage({
        id: 'rt-multiple-workflows',
        title: 'Multiple workflows',
        status: 'later',
        currentState: 'Один bridge workflow; multi-workflow factory нет.',
        nextStep: 'После DAG/pool.',
        priority: 5,
        evidence: [
          { kind: 'docs', path: 'docs/operations/asi-owner-development-console-v1.md' },
        ],
      }),
      stage({
        id: 'rt-shared-verified-result',
        title: 'Общий проверенный результат',
        status: 'later',
        currentState: 'Коллективная оркестрация / shared verified result не готовы.',
        nextStep: 'После multi-workflow.',
        priority: 5,
        evidence: [
          { kind: 'docs', path: 'docs/asi-chat-runtime-bridge-v1.md' },
        ],
      }),
      stage({
        id: 'rt-provider-adapters',
        title: 'Cursor/Codex/Copilot/Devin provider adapters',
        status: 'later',
        currentState: 'Ingest допускает provider label; multi-adapter factory отсутствует.',
        nextStep: 'Не путать provider field с реальными adapters.',
        priority: 5,
        evidence: [
          { kind: 'code', path: 'src/lib/asi-runtime', note: 'provider label in ingest' },
          { kind: 'test', path: 'src/lib/asi-runtime/__tests__/ingest-schema.test.ts' },
        ],
      }),
      stage({
        id: 'rt-owner-merge-gate',
        title: 'Owner approval перед merge/deploy',
        status: 'done',
        currentState: 'Owner merge gate и Development console решения реализованы.',
        nextStep: 'Любой merge/deploy только через owner approval.',
        priority: 2,
        dashboardHref: '/dashboard/development',
        evidence: [
          { kind: 'code', path: 'src/lib/development/owner-merge-gate.ts' },
          { kind: 'docs', path: 'docs/operations/asi-owner-development-console-v1.md' },
        ],
      }),
    ],
  },
];
