import { type Metadata } from 'next';
import { notFound } from 'next/navigation';
import { generateReport, decodeReportId } from '@/lib/report/generator';
import ReportView from './ReportView';

// ── Metadata ──────────────────────────────────────────────────────────────────

export async function generateMetadata({
  params,
}: {
  params: Promise<{ id: string }>;
}): Promise<Metadata> {
  const { id } = await params;
  let address = 'Location';
  try {
    address = decodeReportId(id);
  } catch { /* ignore */ }

  return {
    title: `Location Revenue Report — ${address} | ASI`,
    description:
      `Market analysis, revenue projections, and rental strategy for ${address}. ` +
      `Generated by ASI location intelligence.`,
    robots: { index: false, follow: false },
  };
}

// ── Page ──────────────────────────────────────────────────────────────────────

export default async function ReportPage({
  params,
}: {
  params: Promise<{ id: string }>;
}) {
  const { id } = await params;

  // Guard: ID must be a non-empty string of reasonable length
  if (!id || id.length > 512) notFound();

  let data;
  try {
    data = generateReport(id);
  } catch {
    notFound();
  }

  return <ReportView data={data} />;
}
