import type { OperationsBookingIntake, OperationsWorkflowStage } from './types';

export const operationsStageLabels: Record<OperationsWorkflowStage, string> = {
  new_inquiry: 'New inquiry / lead',
  booking_intake: 'Booking intake',
  pre_checkin: 'Pre-check-in',
  checkin_today: 'Check-in today',
  in_stay: 'In stay',
  checkout: 'Checkout',
  review_followup: 'Review / follow-up',
  needs_operator: 'Needs operator',
};

export const operationsStageOrder: OperationsWorkflowStage[] = [
  'new_inquiry',
  'booking_intake',
  'pre_checkin',
  'checkin_today',
  'in_stay',
  'checkout',
  'review_followup',
  'needs_operator',
];

export const demoOperationsBookings: OperationsBookingIntake[] = [
  {
    id: 'ops-demo-lead-001',
    guest: {
      guestName: 'Guest A',
      channel: 'telegram',
      externalContactId: 'tg-demo-contact',
    },
    source: 'telegram',
    objectLabel: 'Object pending assignment',
    dates: { checkIn: '2026-05-10', checkOut: '2026-05-12', nights: 2 },
    stage: 'new_inquiry',
    status: 'lead',
    paymentStatus: 'pending',
    checkInStatus: 'not_started',
    checkoutStatus: 'not_started',
    issueStatus: 'none',
    automationMode: 'manual',
    notes: [
      'Demo lead awaiting operator confirmation.',
      'No property facts are attached until object context is selected.',
    ],
    checklist: [
      { id: 'lead-source', label: 'Source channel captured', status: 'done' },
      { id: 'lead-object', label: 'Assign object context', status: 'pending', note: 'Requires property context' },
      { id: 'lead-policy', label: 'Apply object policy', status: 'blocked', note: 'Configured per object policy' },
    ],
    createdAt: '2026-05-08T08:15:00.000Z',
    updatedAt: '2026-05-08T08:45:00.000Z',
    timeline: [
      { id: 'lead-created', label: 'Lead created from communication channel', createdAt: '2026-05-08T08:15:00.000Z' },
      { id: 'lead-waiting', label: 'Waiting for booking intake', detail: 'Demo-only workflow item.', createdAt: '2026-05-08T08:45:00.000Z' },
    ],
  },
  {
    id: 'ops-demo-intake-002',
    guest: {
      guestName: 'Guest B',
      channel: 'email',
      email: 'guest-b@example.invalid',
    },
    source: 'email',
    objectLabel: 'Object DEMO-02',
    propertyId: 'demo-object-02',
    dates: { checkIn: '2026-05-11', checkOut: '2026-05-14', nights: 3 },
    stage: 'booking_intake',
    status: 'intake',
    paymentStatus: 'needs_review',
    checkInStatus: 'requires_property_context',
    checkoutStatus: 'not_started',
    issueStatus: 'none',
    automationMode: 'manual',
    notes: [
      'Payment and guest details are placeholders for Phase 1.',
      'Object policy must be reviewed before any guest-facing instruction.',
    ],
    checklist: [
      { id: 'intake-dates', label: 'Dates captured', status: 'done' },
      { id: 'intake-contact', label: 'Guest contact captured', status: 'done' },
      { id: 'intake-payment', label: 'Payment status reviewed', status: 'pending' },
      { id: 'intake-policy', label: 'Object policy attached', status: 'pending', note: 'Configured per object policy' },
    ],
    communicationReviewId: 'demo-review-email-002',
    communicationSessionId: 'demo-session-email-002',
    createdAt: '2026-05-08T09:00:00.000Z',
    updatedAt: '2026-05-08T09:20:00.000Z',
    timeline: [
      { id: 'intake-started', label: 'Booking intake started', createdAt: '2026-05-08T09:00:00.000Z' },
      { id: 'intake-review', label: 'Operator payment review required', createdAt: '2026-05-08T09:20:00.000Z', tone: 'warn' },
    ],
  },
  {
    id: 'ops-demo-precheckin-003',
    guest: {
      guestName: 'Guest C',
      channel: 'phone',
      phone: '+10000000003',
    },
    source: 'phone',
    objectLabel: 'Object DEMO-03',
    propertyId: 'demo-object-03',
    dates: { checkIn: '2026-05-09', checkOut: '2026-05-13', nights: 4 },
    stage: 'pre_checkin',
    status: 'pre_checkin',
    paymentStatus: 'authorized',
    checkInStatus: 'ready',
    checkoutStatus: 'not_started',
    issueStatus: 'none',
    automationMode: 'semi_automated',
    notes: [
      'Readiness checklist is satisfied in demo state.',
      'Guest instructions remain hidden until object policy is configured.',
    ],
    checklist: [
      { id: 'precheckin-contact', label: 'Guest contact verified', status: 'done' },
      { id: 'precheckin-readiness', label: 'Unit readiness checked', status: 'done' },
      { id: 'precheckin-policy', label: 'Policy-based check-in message prepared', status: 'pending', note: 'Configured per object policy' },
    ],
    communicationReviewId: 'demo-review-phone-003',
    createdAt: '2026-05-07T14:30:00.000Z',
    updatedAt: '2026-05-08T10:05:00.000Z',
    timeline: [
      { id: 'precheckin-created', label: 'Pre-check-in workflow opened', createdAt: '2026-05-07T14:30:00.000Z' },
      { id: 'precheckin-ready', label: 'Marked check-in ready', detail: 'Demo status only.', createdAt: '2026-05-08T10:05:00.000Z', tone: 'success' },
    ],
  },
  {
    id: 'ops-demo-checkin-004',
    guest: {
      guestName: 'Guest D',
      channel: 'telegram',
      externalContactId: 'tg-demo-checkin',
    },
    source: 'telegram',
    objectLabel: 'Object DEMO-04',
    propertyId: 'demo-object-04',
    dates: { checkIn: '2026-05-08', checkOut: '2026-05-10', nights: 2 },
    stage: 'checkin_today',
    status: 'confirmed',
    paymentStatus: 'paid',
    checkInStatus: 'ready',
    checkoutStatus: 'not_started',
    issueStatus: 'none',
    automationMode: 'semi_automated',
    notes: [
      'Check-in is due today.',
      'Access and arrival details must come from configured property policy.',
    ],
    checklist: [
      { id: 'checkin-ready', label: 'Check-in readiness passed', status: 'done' },
      { id: 'checkin-arrival', label: 'Guest arrival confirmation', status: 'pending' },
      { id: 'checkin-access', label: 'Access handling', status: 'pending', note: 'Requires property context' },
    ],
    communicationReviewId: 'demo-review-telegram-004',
    createdAt: '2026-05-06T11:15:00.000Z',
    updatedAt: '2026-05-08T11:15:00.000Z',
    timeline: [
      { id: 'checkin-window', label: 'Moved to check-in today', createdAt: '2026-05-08T06:00:00.000Z' },
      { id: 'checkin-awaiting', label: 'Awaiting guest check-in confirmation', createdAt: '2026-05-08T11:15:00.000Z' },
    ],
  },
  {
    id: 'ops-demo-stay-005',
    guest: {
      guestName: 'Guest E',
      channel: 'direct',
      phone: '+10000000005',
    },
    source: 'direct',
    objectLabel: 'Object DEMO-05',
    propertyId: 'demo-object-05',
    dates: { checkIn: '2026-05-06', checkOut: '2026-05-09', nights: 3 },
    stage: 'in_stay',
    status: 'in_stay',
    paymentStatus: 'paid',
    checkInStatus: 'guest_checked_in',
    checkoutStatus: 'scheduled',
    issueStatus: 'open',
    automationMode: 'fully_automated',
    notes: [
      'Guest is currently in stay.',
      'Open issue uses generic issue tracking only; no property facts are inferred.',
    ],
    checklist: [
      { id: 'stay-checked-in', label: 'Guest checked in', status: 'done' },
      { id: 'stay-support', label: 'Stay support monitored', status: 'pending' },
      { id: 'stay-issue', label: 'Open issue review', status: 'pending', note: 'Operator context required' },
    ],
    communicationReviewId: 'demo-review-direct-005',
    createdAt: '2026-05-05T15:00:00.000Z',
    updatedAt: '2026-05-08T12:25:00.000Z',
    timeline: [
      { id: 'stay-started', label: 'Guest checked in', createdAt: '2026-05-06T15:10:00.000Z', tone: 'success' },
      { id: 'stay-issue', label: 'Issue created', detail: 'Generic support issue for demo workflow.', createdAt: '2026-05-08T12:25:00.000Z', tone: 'warn' },
    ],
  },
  {
    id: 'ops-demo-checkout-006',
    guest: {
      guestName: 'Guest F',
      channel: 'email',
      email: 'guest-f@example.invalid',
    },
    source: 'email',
    objectLabel: 'Object DEMO-06',
    propertyId: 'demo-object-06',
    dates: { checkIn: '2026-05-04', checkOut: '2026-05-08', nights: 4 },
    stage: 'checkout',
    status: 'checked_in',
    paymentStatus: 'paid',
    checkInStatus: 'guest_checked_in',
    checkoutStatus: 'scheduled',
    issueStatus: 'none',
    automationMode: 'semi_automated',
    notes: [
      'Checkout is scheduled today.',
      'Checkout instructions are not shown until configured from object policy.',
    ],
    checklist: [
      { id: 'checkout-scheduled', label: 'Checkout scheduled', status: 'done' },
      { id: 'checkout-confirm', label: 'Guest checkout confirmation', status: 'pending' },
      { id: 'checkout-turnover', label: 'Turnover task placeholder', status: 'pending' },
    ],
    createdAt: '2026-05-03T10:00:00.000Z',
    updatedAt: '2026-05-08T07:30:00.000Z',
    timeline: [
      { id: 'checkout-today', label: 'Moved to checkout column', createdAt: '2026-05-08T07:30:00.000Z' },
    ],
  },
  {
    id: 'ops-demo-followup-007',
    guest: {
      guestName: 'Guest G',
      channel: 'demo',
    },
    source: 'demo',
    objectLabel: 'Object DEMO-07',
    propertyId: 'demo-object-07',
    dates: { checkIn: '2026-05-01', checkOut: '2026-05-04', nights: 3 },
    stage: 'review_followup',
    status: 'followup',
    paymentStatus: 'paid',
    checkInStatus: 'guest_checked_in',
    checkoutStatus: 'completed',
    issueStatus: 'closed',
    automationMode: 'manual',
    notes: [
      'Post-stay follow-up placeholder.',
      'No review prompt is sent automatically in Phase 1.',
    ],
    checklist: [
      { id: 'followup-checkout', label: 'Checkout completed', status: 'done' },
      { id: 'followup-issues', label: 'Issues closed', status: 'done' },
      { id: 'followup-review', label: 'Review/follow-up decision', status: 'pending' },
    ],
    createdAt: '2026-04-30T10:00:00.000Z',
    updatedAt: '2026-05-08T08:00:00.000Z',
    timeline: [
      { id: 'followup-ready', label: 'Ready for post-stay follow-up', createdAt: '2026-05-08T08:00:00.000Z' },
    ],
  },
  {
    id: 'ops-demo-operator-008',
    guest: {
      guestName: 'Guest H',
      channel: 'phone',
      phone: '+10000000008',
    },
    source: 'phone',
    objectLabel: 'Requires property context',
    dates: { checkIn: '2026-05-08', checkOut: '2026-05-09', nights: 1 },
    stage: 'needs_operator',
    status: 'needs_operator',
    paymentStatus: 'needs_review',
    checkInStatus: 'operator_review',
    checkoutStatus: 'not_started',
    issueStatus: 'escalated',
    automationMode: 'manual',
    notes: [
      'Escalated from phone call demo event.',
      'Operator must resolve object and booking context before any policy answer.',
    ],
    checklist: [
      { id: 'operator-context', label: 'Resolve booking/object context', status: 'blocked', note: 'Requires property context' },
      { id: 'operator-review', label: 'Operator review item linked', status: 'done' },
      { id: 'operator-safe-answer', label: 'Guest-facing answer', status: 'blocked', note: 'No accommodation facts may be guessed' },
    ],
    communicationReviewId: 'demo-review-phone-008',
    createdAt: '2026-05-08T13:10:00.000Z',
    updatedAt: '2026-05-08T13:20:00.000Z',
    timeline: [
      { id: 'operator-call', label: 'Phone event escalated to operator', createdAt: '2026-05-08T13:10:00.000Z', tone: 'warn' },
      { id: 'operator-context-needed', label: 'Property context missing', detail: 'Canon-safe handoff required.', createdAt: '2026-05-08T13:20:00.000Z', tone: 'warn' },
    ],
  },
];
