import type { OperationScenario } from './types';

export const operationScenarios: OperationScenario[] = [
  {
    id: 'ops-new-booking',
    type: 'new_booking',
    nameRu: 'Новая бронь на выходные',
    bookingOperationId: 'booking-op-new-booking',
    propertyNameRu: 'Апартаменты у Тверской',
    guestNameRu: 'Анна',
    phaseId: 'booking_intake',
    status: 'active',
    priority: 'normal',
    automationStatus: 'automated',
    channelRu: 'Сайт / форма заявки',
    summaryRu: 'ASI принял бронь, сверил даты и готовит карточку гостя для дальнейшего сценария.',
    nextAction: {
      owner: 'asi',
      labelRu: 'Собрать данные брони и отправить гостю подтверждение',
      dueRu: 'Сейчас',
      handoffRequired: false,
    },
    tasks: [
      {
        id: 'new-booking-context',
        titleRu: 'Создать операционную карточку брони',
        status: 'active',
        automationStatus: 'automated',
      },
      {
        id: 'new-booking-message',
        titleRu: 'Подготовить первое сообщение гостю',
        status: 'queued',
        automationStatus: 'automated',
      },
    ],
    events: [
      {
        id: 'new-booking-received',
        atRu: '10:14',
        actor: 'system',
        titleRu: 'Бронь получена',
        detailRu: 'Источник, даты и объект добавлены в операционный контур.',
        status: 'completed',
      },
      {
        id: 'new-booking-enrich',
        atRu: '10:15',
        actor: 'asi',
        titleRu: 'Контекст собирается',
        detailRu: 'Система проверяет правила объекта и готовит следующий шаг.',
        status: 'active',
      },
    ],
  },
  {
    id: 'ops-guest-question',
    type: 'guest_question',
    nameRu: 'Вопрос гостя о раннем заезде',
    bookingOperationId: 'booking-op-guest-question',
    propertyNameRu: 'Лофт на Белорусской',
    guestNameRu: 'Михаил',
    phaseId: 'guest_classification',
    status: 'waiting_guest',
    priority: 'normal',
    automationStatus: 'semi_automated',
    channelRu: 'Мессенджер',
    summaryRu: 'Гость уточнил ранний заезд. ASI классифицировал запрос и запросил недостающие детали.',
    nextAction: {
      owner: 'guest',
      labelRu: 'Дождаться подтверждения времени прибытия',
      dueRu: 'До 18:00',
      handoffRequired: false,
    },
    tasks: [
      {
        id: 'question-classify',
        titleRu: 'Определить тип запроса',
        status: 'completed',
        automationStatus: 'automated',
      },
      {
        id: 'question-policy',
        titleRu: 'Проверить правила раннего заезда',
        status: 'completed',
        automationStatus: 'automated',
      },
    ],
    events: [
      {
        id: 'question-inbound',
        atRu: '11:02',
        actor: 'guest',
        titleRu: 'Вопрос получен',
        detailRu: 'Гость спросил, можно ли заехать на два часа раньше.',
        status: 'completed',
      },
      {
        id: 'question-reply',
        atRu: '11:03',
        actor: 'asi',
        titleRu: 'Ответ отправлен',
        detailRu: 'Система уточнила время прибытия и сообщила условия раннего заезда.',
        status: 'waiting_guest',
      },
    ],
  },
  {
    id: 'ops-maintenance',
    type: 'maintenance_issue',
    nameRu: 'Инцидент с сантехникой',
    bookingOperationId: 'booking-op-maintenance',
    propertyNameRu: 'Студия у Парка культуры',
    guestNameRu: 'Ольга',
    phaseId: 'stay_support',
    status: 'needs_human',
    priority: 'urgent',
    automationStatus: 'manual_review',
    channelRu: 'Чат гостя',
    summaryRu: 'Гость сообщил о протечке. ASI собрал симптомы, но нужен оператор для решения и подрядчика.',
    nextAction: {
      owner: 'operator',
      labelRu: 'Подтвердить выезд мастера и написать гостю',
      dueRu: '15 минут',
      handoffRequired: true,
    },
    tasks: [
      {
        id: 'maintenance-triage',
        titleRu: 'Собрать описание проблемы',
        status: 'completed',
        automationStatus: 'automated',
      },
      {
        id: 'maintenance-dispatch',
        titleRu: 'Назначить подрядчика',
        status: 'needs_human',
        automationStatus: 'manual_review',
      },
    ],
    events: [
      {
        id: 'maintenance-inbound',
        atRu: '13:40',
        actor: 'guest',
        titleRu: 'Инцидент открыт',
        detailRu: 'Гость отправил сообщение о протечке в ванной.',
        status: 'completed',
      },
      {
        id: 'maintenance-handoff',
        atRu: '13:42',
        actor: 'asi',
        titleRu: 'Передано оператору',
        detailRu: 'Высокий риск ущерба, требуется ручное подтверждение выезда мастера.',
        status: 'needs_human',
      },
    ],
  },
  {
    id: 'ops-checkout',
    type: 'checkout',
    nameRu: 'Выезд сегодня',
    bookingOperationId: 'booking-op-checkout',
    propertyNameRu: 'Апартаменты на Арбате',
    guestNameRu: 'Дмитрий',
    phaseId: 'checkout',
    status: 'active',
    priority: 'normal',
    automationStatus: 'automated',
    channelRu: 'Email + мессенджер',
    summaryRu: 'ASI отправляет инструкции по выезду и ставит проверку объекта после гостя.',
    nextAction: {
      owner: 'asi',
      labelRu: 'Отправить напоминание и создать задачу проверки',
      dueRu: 'За 3 часа до выезда',
      handoffRequired: false,
    },
    tasks: [
      {
        id: 'checkout-reminder',
        titleRu: 'Напомнить правила выезда',
        status: 'active',
        automationStatus: 'automated',
      },
      {
        id: 'checkout-inspection',
        titleRu: 'Запланировать проверку объекта',
        status: 'queued',
        automationStatus: 'semi_automated',
      },
    ],
    events: [
      {
        id: 'checkout-window',
        atRu: '08:30',
        actor: 'system',
        titleRu: 'Окно выезда открыто',
        detailRu: 'Сценарий перешел в фазу выезда.',
        status: 'completed',
      },
      {
        id: 'checkout-message',
        atRu: '08:31',
        actor: 'asi',
        titleRu: 'Напоминание готовится',
        detailRu: 'Гостю будет отправлена инструкция по ключам и времени выезда.',
        status: 'active',
      },
    ],
  },
  {
    id: 'ops-review',
    type: 'review_request',
    nameRu: 'Запрос отзыва после проживания',
    bookingOperationId: 'booking-op-review',
    propertyNameRu: 'Видовая квартира у Москва-Сити',
    guestNameRu: 'Елена',
    phaseId: 'review_follow_up',
    status: 'queued',
    priority: 'low',
    automationStatus: 'automated',
    channelRu: 'Мессенджер',
    summaryRu: 'После закрытия выезда ASI готовит теплый follow-up и запрос отзыва.',
    nextAction: {
      owner: 'asi',
      labelRu: 'Отправить запрос отзыва и отметить гостя для повторного контакта',
      dueRu: 'Через 2 часа',
      handoffRequired: false,
    },
    tasks: [
      {
        id: 'review-message',
        titleRu: 'Подготовить сообщение после проживания',
        status: 'queued',
        automationStatus: 'automated',
      },
      {
        id: 'review-repeat',
        titleRu: 'Оценить потенциал повторного гостя',
        status: 'queued',
        automationStatus: 'automated',
      },
    ],
    events: [
      {
        id: 'review-checkout-closed',
        atRu: '12:10',
        actor: 'system',
        titleRu: 'Выезд закрыт',
        detailRu: 'Сценарий готов к запросу обратной связи.',
        status: 'completed',
      },
    ],
  },
  {
    id: 'ops-escalation',
    type: 'operator_escalation',
    nameRu: 'Эскалация по нестандартному заезду',
    bookingOperationId: 'booking-op-escalation',
    propertyNameRu: 'Дом у воды',
    guestNameRu: 'Игорь',
    phaseId: 'pre_arrival',
    status: 'needs_human',
    priority: 'high',
    automationStatus: 'manual_review',
    channelRu: 'Телефонная заявка',
    summaryRu: 'Гость просит поздний заезд и дополнительное место. ASI собрал контекст, решение за оператором.',
    nextAction: {
      owner: 'operator',
      labelRu: 'Подтвердить условия и выбрать финальный текст ответа',
      dueRu: '30 минут',
      handoffRequired: true,
    },
    tasks: [
      {
        id: 'escalation-policy',
        titleRu: 'Проверить правила объекта',
        status: 'completed',
        automationStatus: 'automated',
      },
      {
        id: 'escalation-decision',
        titleRu: 'Принять операционное решение',
        status: 'needs_human',
        automationStatus: 'manual_review',
      },
    ],
    events: [
      {
        id: 'escalation-inbound',
        atRu: '16:20',
        actor: 'guest',
        titleRu: 'Нестандартный запрос',
        detailRu: 'Гость запросил поздний заезд и дополнительное спальное место.',
        status: 'completed',
      },
      {
        id: 'escalation-context',
        atRu: '16:22',
        actor: 'asi',
        titleRu: 'Контекст подготовлен',
        detailRu: 'Система собрала правила объекта и варианты ответа для оператора.',
        status: 'needs_human',
      },
    ],
  },
];
