import type {
  BookingOperation,
  CleaningTask,
  GuestCommunicationEvent,
  MaintenanceTask,
  OperationAuditEvent,
  OperatorEscalation,
  PropertyListingIntake,
} from './types';

export const propertyListingIntakes: PropertyListingIntake[] = [
  {
    id: 'listing-tverskaya-01',
    ownerNameRu: 'Марина, собственник',
    propertyNameRu: 'Апартаменты у Тверской',
    cityRu: 'Москва',
    addressRu: 'Район Тверская, точный адрес скрыт в публичном демо',
    propertyTypeRu: '1-комнатная квартира',
    capacityRu: '2 гостя, 1 спальня, 1 кровать',
    descriptionRu:
      'Готовая карточка объекта для краткосрочной аренды: описание, правила, доступы, клининг и контакты мастеров собраны один раз.',
    amenitiesRu: ['Wi-Fi', 'Кондиционер', 'Стиральная машина', 'Рабочее место', 'Бесконтактный доступ'],
    houseRulesRu: ['Без вечеринок', 'Не курить', 'Тихие часы после 22:00', 'Животные по согласованию'],
    checkInInstructionsRu: [
      'Заезд после 15:00',
      'Код от подъезда отправляется после подтверждения брони',
      'Ключ находится в smart-lock боксе у двери',
    ],
    checkOutInstructionsRu: [
      'Выезд до 12:00',
      'Оставить ключ в боксе',
      'Проверить окна, свет и воду перед выходом',
    ],
    accessInfoRu: ['Smart-lock бокс у двери', 'Резервный ключ у консьержа', 'Инструкция доступна в карточке гостя'],
    cleaningRulesRu: [
      'Клининг после каждого выезда',
      'Фото кухни и ванной после уборки',
      'Проверка расходников по чек-листу',
    ],
    maintenanceContacts: [
      {
        id: 'contact-plumbing',
        roleRu: 'Сантехник',
        nameRu: 'Алексей',
        phoneRu: '+7 *** ***-14-22',
        availabilityRu: 'Ежедневно 09:00-21:00',
      },
      {
        id: 'contact-electric',
        roleRu: 'Домашний мастер',
        nameRu: 'Илья',
        phoneRu: '+7 *** ***-31-08',
        availabilityRu: 'По заявке, обычно до 2 часов',
      },
    ],
    media: [
      {
        id: 'media-living-room',
        kind: 'photo',
        titleRu: 'Гостиная',
        url: '/operations/mock/living-room.jpg',
        altRu: 'Главное фото гостиной',
        status: 'approved',
        distributionReady: true,
      },
      {
        id: 'media-kitchen',
        kind: 'photo',
        titleRu: 'Кухня',
        url: '/operations/mock/kitchen.jpg',
        altRu: 'Фото кухни для карточки объекта',
        status: 'approved',
        distributionReady: true,
      },
      {
        id: 'media-rules',
        kind: 'document',
        titleRu: 'Правила дома',
        url: '/operations/mock/house-rules.pdf',
        altRu: 'PDF с правилами дома',
        status: 'uploaded',
        distributionReady: false,
      },
    ],
    channelMetadata: [
      {
        channelId: 'avito',
        externalListingId: 'AVITO-MOCK-1042',
        titleRu: 'Квартира посуточно у Тверской',
        commissionRu: 'по тарифу площадки',
        minStayNights: 1,
        instantBookEnabled: false,
      },
      {
        channelId: 'ostrovok',
        titleRu: 'Апартаменты у Тверской',
        commissionRu: 'по тарифу площадки',
        minStayNights: 1,
        instantBookEnabled: false,
      },
      {
        channelId: 'yandex_travel',
        titleRu: 'Апартаменты у Тверской',
        commissionRu: 'по тарифу площадки',
        minStayNights: 1,
        instantBookEnabled: false,
      },
      {
        channelId: 'sutochno',
        titleRu: 'Квартира посуточно у Тверской',
        commissionRu: 'по тарифу площадки',
        minStayNights: 1,
        instantBookEnabled: false,
      },
      {
        channelId: 'booking_ical',
        titleRu: 'Booking / iCal placeholder',
        commissionRu: 'availability only',
        minStayNights: 1,
        instantBookEnabled: false,
      },
    ],
    distributionTargets: [
      {
        id: 'target-avito',
        channelId: 'avito',
        channelNameRu: 'Авито',
        syncStatus: 'synced',
        connected: true,
        lastSyncRu: 'Сегодня, 09:40',
        nextActionRu: 'Следить за изменениями карточки',
        syncedFieldsRu: ['Описание', 'Фото', 'Правила', 'Удобства', 'Инструкции заезда'],
        pendingFieldsRu: [],
      },
      {
        id: 'target-ostrovok',
        channelId: 'ostrovok',
        channelNameRu: 'Островок',
        syncStatus: 'queued',
        connected: true,
        lastSyncRu: 'Вчера, 18:10',
        nextActionRu: 'Отправить обновленные правила и фото',
        syncedFieldsRu: ['Название', 'Описание', 'Удобства'],
        pendingFieldsRu: ['Фото кухни', 'Правила дома', 'Инструкции выезда'],
      },
      {
        id: 'target-yandex',
        channelId: 'yandex_travel',
        channelNameRu: 'Яндекс Путешествия',
        syncStatus: 'ready',
        connected: true,
        nextActionRu: 'Поставить карточку в очередь отправки',
        syncedFieldsRu: [],
        pendingFieldsRu: ['Полная карточка объекта'],
      },
      {
        id: 'target-sutochno',
        channelId: 'sutochno',
        channelNameRu: 'Суточно',
        syncStatus: 'syncing',
        connected: true,
        nextActionRu: 'Демо-синхронизация полей карточки',
        syncedFieldsRu: ['Описание', 'Фото'],
        pendingFieldsRu: ['Контакты', 'Инструкции выезда'],
      },
      {
        id: 'target-booking-ical',
        channelId: 'booking_ical',
        channelNameRu: 'Booking / iCal placeholder',
        syncStatus: 'draft',
        connected: false,
        nextActionRu: 'Позже подключить iCal availability bridge',
        syncedFieldsRu: [],
        pendingFieldsRu: ['Календарь доступности', 'ID внешнего листинга'],
      },
    ],
    intakeStatus: 'ready',
    auditEvents: [
      {
        id: 'listing-uploaded',
        atRu: '09:10',
        actor: 'partner',
        titleRu: 'Собственник загрузил данные',
        detailRu: 'Описание, фото, правила дома, доступы, клининг и контакты мастеров добавлены в одну карточку.',
        status: 'completed',
      },
      {
        id: 'listing-prepared',
        atRu: '09:28',
        actor: 'asi',
        titleRu: 'Карточка подготовлена к распределению',
        detailRu: 'ASI нормализовал поля под channel-manager слой и отметил pending-поля по каналам.',
        status: 'active',
      },
    ],
  },
];

export const cleaningTasks: CleaningTask[] = [
  {
    id: 'cleaning-tverskaya-01',
    operationId: 'booking-op-new-booking',
    propertyListingId: 'listing-tverskaya-01',
    titleRu: 'Клининг перед заездом Анны',
    assignedToRu: 'Команда клининга: смена А',
    scheduledForRu: 'Сегодня, 13:00-15:00',
    status: 'assigned',
    checklistRu: ['Постель и полотенца', 'Кухня', 'Ванная', 'Расходники', 'Фото после уборки'],
    notesRu: 'Задача создана автоматически после новой брони.',
  },
  {
    id: 'cleaning-checkout-01',
    operationId: 'booking-op-checkout',
    propertyListingId: 'listing-tverskaya-01',
    titleRu: 'Клининг после выезда Дмитрия',
    assignedToRu: 'Команда клининга: смена B',
    scheduledForRu: 'Сегодня, 12:30-14:30',
    status: 'queued',
    checklistRu: ['Проверить ключ', 'Осмотр кухни', 'Фото ванной', 'Отметить расходники'],
    notesRu: 'Будет активирована после подтверждения выезда.',
  },
];

export const maintenanceTasks: MaintenanceTask[] = [
  {
    id: 'maintenance-plumbing-01',
    operationId: 'booking-op-maintenance',
    propertyListingId: 'listing-tverskaya-01',
    titleRu: 'Выезд сантехника',
    assignedToRu: 'Алексей, сантехник',
    scheduledForRu: 'Сегодня, ближайшее окно',
    priority: 'urgent',
    status: 'needs_human',
    issueRu: 'Гость сообщил о протечке в ванной.',
    handoffRequired: true,
  },
  {
    id: 'maintenance-prearrival-01',
    operationId: 'booking-op-escalation',
    propertyListingId: 'listing-tverskaya-01',
    titleRu: 'Подготовить дополнительное спальное место',
    assignedToRu: 'Илья, домашний мастер',
    scheduledForRu: 'Завтра до 14:00',
    priority: 'high',
    status: 'assigned',
    issueRu: 'Гость запросил дополнительное место перед поздним заездом.',
    handoffRequired: false,
  },
];

export const guestCommunicationEvents: GuestCommunicationEvent[] = [
  {
    id: 'comm-booking-confirmation',
    operationId: 'booking-op-new-booking',
    atRu: '10:16',
    channelRu: 'Сайт / email',
    direction: 'outbound',
    actor: 'asi',
    intentRu: 'Подтверждение брони',
    messageRu: 'ASI отправил гостю подтверждение и список следующих шагов.',
    automated: true,
    status: 'completed',
  },
  {
    id: 'comm-early-checkin',
    operationId: 'booking-op-guest-question',
    atRu: '11:03',
    channelRu: 'Мессенджер',
    direction: 'outbound',
    actor: 'asi',
    intentRu: 'Ранний заезд',
    messageRu: 'ASI уточнил время прибытия и применил правила объекта.',
    automated: true,
    status: 'waiting_guest',
  },
  {
    id: 'comm-maintenance',
    operationId: 'booking-op-maintenance',
    atRu: '13:42',
    channelRu: 'Чат гостя',
    direction: 'outbound',
    actor: 'asi',
    intentRu: 'Инцидент обслуживания',
    messageRu: 'ASI подтвердил получение обращения и передал решение оператору.',
    automated: true,
    status: 'needs_human',
  },
  {
    id: 'comm-review',
    operationId: 'booking-op-review',
    atRu: '14:10',
    channelRu: 'Мессенджер',
    direction: 'outbound',
    actor: 'asi',
    intentRu: 'Отзыв и повторный контакт',
    messageRu: 'ASI подготовил запрос отзыва и пометил гостя для follow-up.',
    automated: true,
    status: 'queued',
  },
];

export const operatorEscalations: OperatorEscalation[] = [
  {
    id: 'escalation-maintenance-01',
    operationId: 'booking-op-maintenance',
    status: 'open',
    reasonRu: 'Риск ущерба и нужен выезд мастера.',
    assignedToRu: 'Оператор смены',
    createdAtRu: '13:42',
    decisionNeededRu: 'Подтвердить мастера и текст компенсации гостю.',
  },
  {
    id: 'escalation-checkin-01',
    operationId: 'booking-op-escalation',
    status: 'open',
    reasonRu: 'Нестандартный поздний заезд и дополнительное место.',
    assignedToRu: 'Оператор смены',
    createdAtRu: '16:22',
    decisionNeededRu: 'Разрешить исключение и выбрать финальный ответ.',
  },
];

export const bookingAuditEvents: OperationAuditEvent[] = [
  {
    id: 'audit-booking-received',
    atRu: '10:14',
    actor: 'system',
    titleRu: 'Бронь принята',
    detailRu: 'Новая бронь создала booking operation и поставила клининг в очередь.',
    status: 'completed',
  },
  {
    id: 'audit-cleaning-assigned',
    atRu: '10:18',
    actor: 'asi',
    titleRu: 'Клининг назначен',
    detailRu: 'Команда клининга получила задачу и чек-лист подготовки.',
    status: 'active',
  },
  {
    id: 'audit-maintenance-assigned',
    atRu: '13:43',
    actor: 'operator',
    titleRu: 'Мастер выбран',
    detailRu: 'Домашний мастер назначен на операционную задачу.',
    status: 'needs_human',
  },
  {
    id: 'audit-review-ready',
    atRu: '14:10',
    actor: 'asi',
    titleRu: 'Follow-up готов',
    detailRu: 'ASI подготовил запрос отзыва и повторную коммуникацию.',
    status: 'queued',
  },
];

export const bookingOperations: BookingOperation[] = [
  {
    id: 'booking-op-new-booking',
    scenarioId: 'ops-new-booking',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2408',
    sourceChannelId: 'direct_site',
    sourceChannelRu: 'Прямой сайт',
    guestNameRu: 'Анна',
    guestTypeRu: 'Новый гость',
    requestClassRu: 'Стандартная бронь',
    checkInRu: 'Пятница, 15:00',
    checkOutRu: 'Воскресенье, 12:00',
    guestsCount: 2,
    phaseId: 'booking_intake',
    status: 'active',
    nextAction: {
      owner: 'asi',
      labelRu: 'Подтвердить бронь и запустить подготовку объекта',
      dueRu: 'Сейчас',
      handoffRequired: false,
    },
    cleaningTaskIds: ['cleaning-tverskaya-01'],
    maintenanceTaskIds: [],
    communicationEventIds: ['comm-booking-confirmation'],
    auditEventIds: ['audit-booking-received', 'audit-cleaning-assigned'],
  },
  {
    id: 'booking-op-guest-question',
    scenarioId: 'ops-guest-question',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2409',
    sourceChannelId: 'airbnb',
    sourceChannelRu: 'Airbnb',
    guestNameRu: 'Михаил',
    guestTypeRu: 'Новый гость',
    requestClassRu: 'Вопрос о раннем заезде',
    checkInRu: 'Завтра, 15:00',
    checkOutRu: 'Через 3 дня, 12:00',
    guestsCount: 1,
    phaseId: 'guest_classification',
    status: 'waiting_guest',
    nextAction: {
      owner: 'guest',
      labelRu: 'Дождаться подтверждения времени прибытия',
      dueRu: 'До 18:00',
      handoffRequired: false,
    },
    cleaningTaskIds: [],
    maintenanceTaskIds: [],
    communicationEventIds: ['comm-early-checkin'],
    auditEventIds: [],
  },
  {
    id: 'booking-op-maintenance',
    scenarioId: 'ops-maintenance',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2388',
    sourceChannelId: 'booking_com',
    sourceChannelRu: 'Booking.com',
    guestNameRu: 'Ольга',
    guestTypeRu: 'Гость в проживании',
    requestClassRu: 'Инцидент обслуживания',
    checkInRu: 'Вчера, 15:00',
    checkOutRu: 'Завтра, 12:00',
    guestsCount: 2,
    phaseId: 'stay_support',
    status: 'needs_human',
    nextAction: {
      owner: 'operator',
      labelRu: 'Подтвердить выезд сантехника и сообщение гостю',
      dueRu: '15 минут',
      handoffRequired: true,
    },
    cleaningTaskIds: [],
    maintenanceTaskIds: ['maintenance-plumbing-01'],
    communicationEventIds: ['comm-maintenance'],
    auditEventIds: ['audit-maintenance-assigned'],
    operatorEscalationId: 'escalation-maintenance-01',
  },
  {
    id: 'booking-op-checkout',
    scenarioId: 'ops-checkout',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2377',
    sourceChannelId: 'ostrovok',
    sourceChannelRu: 'Островок',
    guestNameRu: 'Дмитрий',
    guestTypeRu: 'Новый гость',
    requestClassRu: 'Плановый выезд',
    checkInRu: 'Понедельник, 15:00',
    checkOutRu: 'Сегодня, 12:00',
    guestsCount: 2,
    phaseId: 'checkout',
    status: 'active',
    nextAction: {
      owner: 'asi',
      labelRu: 'Подтвердить выезд и активировать клининг',
      dueRu: 'За 3 часа до выезда',
      handoffRequired: false,
    },
    cleaningTaskIds: ['cleaning-checkout-01'],
    maintenanceTaskIds: [],
    communicationEventIds: [],
    auditEventIds: [],
  },
  {
    id: 'booking-op-review',
    scenarioId: 'ops-review',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2364',
    sourceChannelId: 'avito',
    sourceChannelRu: 'Avito',
    guestNameRu: 'Елена',
    guestTypeRu: 'Потенциальный повторный гость',
    requestClassRu: 'Отзыв после проживания',
    checkInRu: 'Прошлая пятница',
    checkOutRu: 'Сегодня, 12:00',
    guestsCount: 1,
    phaseId: 'review_follow_up',
    status: 'queued',
    nextAction: {
      owner: 'asi',
      labelRu: 'Отправить запрос отзыва и follow-up',
      dueRu: 'Через 2 часа',
      handoffRequired: false,
    },
    cleaningTaskIds: [],
    maintenanceTaskIds: [],
    communicationEventIds: ['comm-review'],
    auditEventIds: ['audit-review-ready'],
  },
  {
    id: 'booking-op-escalation',
    scenarioId: 'ops-escalation',
    propertyListingId: 'listing-tverskaya-01',
    bookingCode: 'ASI-2410',
    sourceChannelId: 'direct_site',
    sourceChannelRu: 'Телефонная заявка',
    guestNameRu: 'Игорь',
    guestTypeRu: 'Семейный гость',
    requestClassRu: 'Исключение по условиям заезда',
    checkInRu: 'Завтра, после 23:00',
    checkOutRu: 'Через 5 дней, 12:00',
    guestsCount: 3,
    phaseId: 'pre_arrival',
    status: 'needs_human',
    nextAction: {
      owner: 'operator',
      labelRu: 'Разрешить исключение и подтвердить подготовку мастера',
      dueRu: '30 минут',
      handoffRequired: true,
    },
    cleaningTaskIds: [],
    maintenanceTaskIds: ['maintenance-prearrival-01'],
    communicationEventIds: [],
    auditEventIds: [],
    operatorEscalationId: 'escalation-checkin-01',
  },
];
