'use client';
import { useEffect, useState } from 'react';
import { onboardingSteps, type OnboardingData, type OnboardingStep } from '@/lib/ops-v17/types';

const labels: Record<OnboardingStep, string> = { business: 'Компания', owner: 'Владелец', properties: 'Объекты', units: 'Помещения', operations: 'Работа на объекте', channel_manager: 'Менеджер каналов', communications: 'Связь', legal_payments: 'Документы и оплата', staff: 'Команда', verification: 'Проверка', launch: 'Запуск' };
type Workspace = { onboarding: { data: OnboardingData; current_step: OnboardingStep }; progress: { percentage: number; missing: Record<string, string[]> }; readiness: { status: string; percentage: number; blockingItems: string[]; warnings: string[]; nextAction: string; initializedModules: string[] }; modules: { key: string; status: string }[] };

export default function OpsV17Workspace() {
  const [workspace, setWorkspace] = useState<Workspace | null>(null); const [step, setStep] = useState<OnboardingStep>('business'); const [draft, setDraft] = useState<OnboardingData>({}); const [busy, setBusy] = useState(false); const [message, setMessage] = useState('');
  const load = async () => { const res = await fetch('/api/dashboard/ops-v17', { cache: 'no-store' }); const body = await res.json(); if (body.workspace) { setWorkspace(body.workspace); setDraft(body.workspace.onboarding.data); setStep(body.workspace.onboarding.current_step); } };
  useEffect(() => { void load(); }, []);
  const patch = (value: Partial<OnboardingData>) => setDraft((current) => ({ ...current, ...value }));
  const save = async () => { setBusy(true); setMessage(''); const res = await fetch('/api/dashboard/ops-v17', { method: 'PATCH', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ step, data: draft }) }); setBusy(false); setMessage(res.ok ? 'Сохранено. Можно продолжить позже.' : 'Не удалось сохранить.'); if (res.ok) await load(); };
  const activate = async () => { setBusy(true); const res = await fetch('/api/dashboard/ops-v17/action', { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ action: 'activate' }) }); setBusy(false); setMessage(res.ok ? 'Пилот запущен.' : 'Запуск пока недоступен. Проверьте блокеры.'); await load(); };
  const value = (key: string, current?: string) => <input value={current ?? ''} onChange={(e) => { const v = e.target.value; if (step === 'business') patch({ business: { ...draft.business, [key]: v } }); if (step === 'owner') patch({ owner: { ...draft.owner, [key]: v } }); if (step === 'operations') patch({ operations: { ...draft.operations, [key]: v } }); if (step === 'communications') patch({ communications: { ...draft.communications, [key]: v } }); if (step === 'legal_payments') patch({ legalPayments: { ...draft.legalPayments, [key]: v } }); }} className="mt-1 w-full rounded-lg border border-slate-300 px-3 py-2" />;
  const missing = workspace?.progress.missing[step] ?? [];
  const fields = (() => {
    if (step === 'business') return <><label>Название компании{value('name', draft.business?.name)}</label><details><summary>Дополнительные сведения</summary><label>Юридическое название{value('legalName', draft.business?.legalName)}</label></details></>;
    if (step === 'owner') return <><label>Имя владельца{value('name', draft.owner?.name)}</label><label>Телефон{value('phone', draft.owner?.phone)}</label><label>Эл. почта{value('email', draft.owner?.email)}</label></>;
    if (step === 'properties') return <ListEditor title="Объекты" rows={draft.properties ?? []} onChange={(rows) => patch({ properties: rows.map((r, i) => ({ key: r.key || `property-${i + 1}`, name: r.name, address: r.address })) })} fields={['name', 'address']} />;
    if (step === 'units') return <ListEditor title="Помещения" rows={draft.units ?? []} onChange={(rows) => patch({ units: rows.map((r, i) => ({ key: r.key || `unit-${i + 1}`, propertyKey: r.propertyKey ?? '', name: r.name })) })} fields={['propertyKey', 'name']} />;
    if (step === 'operations') return <><label>Время заезда{value('checkInTime', draft.operations?.checkInTime)}</label><label>Время выезда{value('checkOutTime', draft.operations?.checkOutTime)}</label><label>Правила уборки{value('cleaningRule', draft.operations?.cleaningRule)}</label><details><summary>Дополнительные правила</summary>{value('linenRule', draft.operations?.linenRule)}{value('inspectionRule', draft.operations?.inspectionRule)}{value('maintenanceRule', draft.operations?.maintenanceRule)}</details></>;
    if (step === 'channel_manager') return <><label>Система<select value={draft.channelManager?.provider ?? ''} onChange={(e) => patch({ channelManager: { ...draft.channelManager, provider: e.target.value } })} className="mt-1 w-full rounded-lg border p-2"><option value="">Выберите</option><option value="manual_import">Импорт из файла</option><option value="bnovo">Bnovo — требуется подключение</option><option value="realtycalendar">RealtyCalendar — требуется подключение</option><option value="travelline">TravelLine — требуется подключение</option></select></label><label>Ссылка на сохранённые данные доступа (не пароль)<input className="mt-1 w-full rounded-lg border p-2" value={draft.channelManager?.credentialsRef ?? ''} onChange={(e) => patch({ channelManager: { ...draft.channelManager, credentialsRef: e.target.value } })} /></label><label className="flex gap-2"><input type="checkbox" checked={draft.channelManager?.snapshotReady ?? false} onChange={(e) => patch({ channelManager: { ...draft.channelManager, snapshotReady: e.target.checked, status: e.target.checked ? 'synchronized' : 'configuration_required' } })} />Файл для импорта подготовлен</label></>;
    if (step === 'communications') return <><label>Связь с гостями{value('guestChannel', draft.communications?.guestChannel)}</label><label>Связь с сотрудниками{value('workerChannel', draft.communications?.workerChannel)}</label><p className="text-sm text-amber-700">Отправка сообщений выключена до отдельного включения для пилота.</p></>;
    if (step === 'legal_payments') return <><label>Документы{value('legalMode', draft.legalPayments?.legalMode)}</label><label>Депозит{value('depositMode', draft.legalPayments?.depositMode)}</label><label>МВД{value('mvdMode', draft.legalPayments?.mvdMode)}</label></>;
    if (step === 'staff') return <ListEditor title="Сотрудники" rows={draft.staff ?? []} onChange={(rows) => patch({ staff: rows.map((r, i) => ({ key: r.key || `staff-${i + 1}`, name: r.name, role: (r.role || 'cleaner') as never, contact: r.contact, propertyKeys: (r.propertyKeys || '').split(',').filter(Boolean) })) })} fields={['name', 'role', 'contact', 'propertyKeys']} />;
    if (step === 'verification') return <p>Проверьте доступ, ключи, Wi‑Fi, электричество, воду, отопление, технику, кровати и бельё, ванную, расходники, пожарную безопасность, фотографии и экстренные контакты. Проблемы создают задачу на ремонт и требуют повторной проверки.</p>;
    return <Readiness workspace={workspace} onActivate={activate} busy={busy} />;
  })();
  return <main className="mx-auto max-w-6xl space-y-6"><header><h1 className="text-3xl font-bold">Запуск объектов</h1><p className="text-slate-600">Заполните данные один раз. ASI подготовит рабочие модули и покажет только то, что мешает запуску.</p></header><div className="rounded-xl border bg-white p-4"><div className="flex justify-between text-sm"><span>Готово</span><b>{workspace?.progress.percentage ?? 0}%</b></div><div className="mt-2 h-2 rounded bg-slate-100"><div className="h-2 rounded bg-emerald-500" style={{ width: `${workspace?.progress.percentage ?? 0}%` }} /></div></div><nav className="flex gap-2 overflow-x-auto pb-2">{onboardingSteps.map((s) => <button key={s} onClick={() => setStep(s)} className={`whitespace-nowrap rounded-full px-3 py-2 text-sm ${s === step ? 'bg-slate-900 text-white' : 'bg-white border'}`}>{labels[s]}</button>)}</nav><section className="space-y-4 rounded-xl border bg-white p-6"><h2 className="text-xl font-semibold">{labels[step]}</h2>{missing.length ? <div className="rounded-lg bg-amber-50 p-3 text-sm text-amber-900">Не хватает: {missing.join(', ')}</div> : null}<div className="grid gap-4">{fields}</div>{step !== 'launch' ? <button disabled={busy} onClick={() => void save()} className="rounded-lg bg-emerald-700 px-4 py-2 text-white disabled:opacity-50">{busy ? 'Сохраняем…' : 'Сохранить шаг'}</button> : null}{message ? <p role="status" className="text-sm">{message}</p> : null}</section></main>;
}

function ListEditor({ title, rows, onChange, fields }: { title: string; rows: Record<string, any>[]; onChange: (rows: Record<string, string>[]) => void; fields: string[] }) { const normalized = rows.map((r) => Object.fromEntries(Object.entries(r).map(([k, v]) => [k, Array.isArray(v) ? v.join(',') : String(v ?? '')]))); return <div><div className="space-y-3">{normalized.map((row, i) => <div key={i} className="grid gap-2 rounded-lg border p-3 sm:grid-cols-2">{fields.map((field) => <label key={field} className="text-sm">{field}<input className="mt-1 w-full rounded border p-2" value={row[field] ?? ''} onChange={(e) => { const next = normalized.map((r) => ({ ...r })); next[i][field] = e.target.value; onChange(next); }} /></label>)}</div>)}</div><button type="button" onClick={() => onChange([...normalized, {}])} className="mt-3 rounded border px-3 py-2">Добавить: {title.toLowerCase()}</button></div>; }
function Readiness({ workspace, onActivate, busy }: { workspace: Workspace | null; onActivate: () => void; busy: boolean }) { const r = workspace?.readiness; return <div className="space-y-4"><div className="rounded-lg bg-slate-50 p-4"><p className="text-sm">Готовность к запуску</p><p className="text-3xl font-bold">{r?.percentage ?? 0}%</p><p>{r?.nextAction}</p></div>{r?.blockingItems.length ? <div><h3 className="font-semibold">Что мешает запуску</h3><ul className="list-disc pl-5">{r.blockingItems.map((x) => <li key={x}>{x}</li>)}</ul></div> : <button disabled={busy} onClick={onActivate} className="rounded-lg bg-emerald-700 px-4 py-2 text-white">Активировать пилот</button>}<details><summary>Подготовленные модули</summary><p>{r?.initializedModules.join(', ') || 'Пока нет'}</p></details></div>; }
