import { describe, expect, it } from 'vitest';
import { planBookingOpsAutomation, type BookingAutomationSnapshot } from '../booking-automation-planner';
import { sanitizeOperatorAlertMetadata } from '../operator-alerts';
import { sanitizeBookingOpsEventMetadata } from '../events';

const NOW = '2026-07-13T09:00:00.000Z';
function snapshot(patch: Partial<BookingAutomationSnapshot> = {}): BookingAutomationSnapshot {
  return {
    bookingId: '11111111-1111-4111-8111-111111111111', accountId: 'account-1', propertyId: 'property-1', now: NOW,
    lifecycle: { exists: true },
    guestIntake: { exists: true, status: 'completed', missingFields: [], requestPrepared: true, policy: null },
    legal: { documentsRequired: false, documents: [], contractRequired: false, contractStatus: null, depositRequired: false, depositStatus: null, mvdRequired: false, mvdStatus: null, canonicalDataComplete: true },
    checkin: { instructionsStatus: 'sent', arrivalStatus: 'confirmed', prerequisitesComplete: true },
    physical: { tasksExist: true, cleaningStatus: 'verified', deterministicCleaner: null, readinessStatus: 'approved', physicalStateChanged: false, autoApprovalAuthorized: false },
    retry: { nextRetryAt: null, attemptCount: 0, maxAttempts: 3, lastAction: null, lastErrorCode: null },
    ...patch,
  };
}
const find = (value: BookingAutomationSnapshot, code: string) => planBookingOpsAutomation(value).find((item) => item.code === code);

describe('planBookingOpsAutomation', () => {
  it('initializes a missing lifecycle automatically', () => expect(find(snapshot({ lifecycle: { exists: false } }), 'initialize_lifecycle')?.disposition).toBe('execute'));
  it('prepares one guest data request when data is missing', () => expect(planBookingOpsAutomation(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: false } })).filter((item) => item.code === 'prepare_guest_data_request')).toHaveLength(1));
  it('reuses an existing allowed request and waits instead of duplicating it', () => expect(find(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true, policy: { code: 'allowed' } } }), 'prepare_guest_data_request')).toMatchObject({ disposition: 'waiting_external', reasonCode: 'communication_queued' }));
  it('turns review-required communication into approval handoff', () => expect(find(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true, policy: { code: 'review_required' } } }), 'prepare_guest_data_request')).toMatchObject({ disposition: 'approval_required', requiresApproval: true }));
  it('schedules quiet-hours retry without handoff', () => expect(find(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true, policy: { code: 'quiet_hours', retryAt: '2026-07-13T18:00:00.000Z' } } }), 'prepare_guest_data_request')).toMatchObject({ disposition: 'retry_scheduled', retryAt: '2026-07-13T18:00:00.000Z' }));
  it('schedules rate-limit retry without handoff', () => expect(find(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true, policy: { code: 'rate_limited', retryAt: '2026-07-13T10:00:00.000Z' } } }), 'prepare_guest_data_request')?.disposition).toBe('retry_scheduled'));
  it('creates one unsafe-content exception', () => expect(planBookingOpsAutomation(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true, policy: { code: 'unsafe', reasonCode: 'unsafe_content' } } })).filter((item) => item.reasonCode === 'unsafe_content')).toHaveLength(1));
  it('does not hand off normal waiting for guest input', () => expect(find(snapshot({ guestIntake: { exists: true, status: 'waiting_for_guest', missingFields: ['phone'], requestPrepared: true } }), 'prepare_guest_data_request')?.disposition).toBe('waiting_external'));
  it('requests documents but never plans verification', () => { const plan = planBookingOpsAutomation(snapshot({ legal: { ...snapshot().legal, documentsRequired: true } })); expect(plan).toContainEqual(expect.objectContaining({ code: 'prepare_documents_request', disposition: 'execute' })); expect(plan.some((item) => item.reasonCode.includes('verify'))).toBe(false); });
  it('prepares a contract but never marks it signed', () => expect(find(snapshot({ legal: { ...snapshot().legal, contractRequired: true, contractStatus: 'not_started' } }), 'prepare_contract')).toMatchObject({ disposition: 'execute', reasonCode: 'contract_not_prepared' }));
  it('prepares a deposit request but never marks it paid', () => expect(find(snapshot({ legal: { ...snapshot().legal, depositRequired: true, depositStatus: 'not_requested' } }), 'prepare_deposit_request')).toMatchObject({ disposition: 'execute', reasonCode: 'deposit_not_requested' }));
  it('prepares an MVD draft but never submits it', () => expect(find(snapshot({ legal: { ...snapshot().legal, mvdRequired: true, mvdStatus: 'not_started' } }), 'prepare_mvd_draft')).toMatchObject({ disposition: 'execute', reasonCode: 'mvd_not_prepared' }));
  it('blocks check-in instruction preparation on incomplete prerequisites', () => expect(find(snapshot({ checkin: { instructionsStatus: 'not_prepared', arrivalStatus: 'unknown', prerequisitesComplete: false } }), 'prepare_checkin_instructions')?.disposition).toBe('no_action'));
  it('prepares check-in instructions when prerequisites are complete', () => expect(find(snapshot({ checkin: { instructionsStatus: 'not_prepared', arrivalStatus: 'unknown', prerequisitesComplete: true } }), 'prepare_checkin_instructions')?.disposition).toBe('execute'));
  it('creates no_eligible_cleaner handoff without a deterministic source', () => expect(find(snapshot({ physical: { ...snapshot().physical, cleaningStatus: 'pending' } }), 'assign_cleaner')).toMatchObject({ disposition: 'handoff_required', reasonCode: 'no_eligible_cleaner' }));
  it('assigns a deterministic cleaner once and never advances real cleaning facts', () => { const planned = find(snapshot({ physical: { ...snapshot().physical, cleaningStatus: 'pending', deterministicCleaner: { assignedToName: 'Executor' } } }), 'assign_cleaner'); expect(planned).toMatchObject({ disposition: 'execute', safeMetadata: { assignedToName: 'Executor' } }); expect(planBookingOpsAutomation(snapshot({ physical: { ...snapshot().physical, cleaningStatus: 'assigned' } })).some((item) => ['in_progress', 'completed', 'verified'].includes(item.reasonCode))).toBe(false); });
  it('recomputes stale physical readiness automatically', () => expect(find(snapshot({ physical: { ...snapshot().physical, physicalStateChanged: true } }), 'recompute_physical_readiness')?.disposition).toBe('execute'));
  it('requires approval at ready_for_review without an explicit auto policy', () => expect(find(snapshot({ physical: { ...snapshot().physical, readinessStatus: 'ready_for_review' } }), 'approve_physical_readiness')).toMatchObject({ disposition: 'approval_required', reasonCode: 'physical_readiness_approval_required' }));
  it('does not retry before nextRetryAt', () => expect(planBookingOpsAutomation(snapshot({ retry: { nextRetryAt: '2026-07-13T10:00:00.000Z', attemptCount: 1, maxAttempts: 3, lastAction: 'prepare_contract', lastErrorCode: 'transient' } }))).toEqual([expect.objectContaining({ disposition: 'retry_scheduled', retryAt: '2026-07-13T10:00:00.000Z' })]));
  it('bounds retries and creates one exhaustion handoff', () => expect(planBookingOpsAutomation(snapshot({ retry: { nextRetryAt: null, attemptCount: 3, maxAttempts: 3, lastAction: 'prepare_contract', lastErrorCode: 'transient' } })).filter((item) => item.reasonCode === 'retry_exhausted')).toHaveLength(1));
  it('plans at most five executable actions and never mutates one gate twice', () => { const plan = planBookingOpsAutomation(snapshot({ lifecycle: { exists: false }, guestIntake: { exists: false, status: 'not_started', missingFields: ['phone'], requestPrepared: false }, legal: { documentsRequired: true, documents: [], contractRequired: true, contractStatus: 'not_started', depositRequired: true, depositStatus: 'not_requested', mvdRequired: true, mvdStatus: 'not_started', canonicalDataComplete: true }, checkin: { instructionsStatus: 'not_prepared', arrivalStatus: 'unknown', prerequisitesComplete: true }, physical: { ...snapshot().physical, tasksExist: false, physicalStateChanged: true } }), 5); const executable = plan.filter((item) => item.disposition === 'execute'); expect(executable.length).toBeLessThanOrEqual(5); expect(new Set(executable.map((item) => item.gateKey).filter(Boolean)).size).toBe(executable.map((item) => item.gateKey).filter(Boolean).length); });
  it('is deterministic for the same snapshot and time', () => { const input = snapshot({ lifecycle: { exists: false } }); expect(planBookingOpsAutomation(input)).toEqual(planBookingOpsAutomation(input)); });
  it('removes PII and secrets from alert metadata', () => expect(sanitizeOperatorAlertMetadata({ guestName: 'Guest', phone: 'secret', accessCode: '1234', failureCode: 'unsafe_content', requiresApproval: true })).toEqual({ failureCode: 'unsafe_content', requiresApproval: true }));
  it('removes PII and message content from audit metadata', () => expect(sanitizeBookingOpsEventMetadata({ messageText: 'secret', documentNumber: '123', actionCode: 'prepare_contract', reasonCode: 'contract_not_prepared' })).toEqual({ actionCode: 'prepare_contract', reasonCode: 'contract_not_prepared' }));
});
